name: CI

on: [push, pull_request]

jobs:
  build:
    name: JDK ${{ matrix.java_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [16, 17-ea]
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - name: Generate cache key
      run: ./checksum.sh checksum.txt
    - uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ matrix.java_version }}-${{ matrix.job }}-${{ hashFiles('checksum.txt') }}
        restore-keys: |
          ${{ runner.os }}-gradle-${{ matrix.java_version }}-${{ matrix.job }}-
    - name: Install JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java_version }}
    - name: Configure Gradle
      # Initial gradle configuration, install dependencies, etc
      run: ./gradlew help
    - name: Build project
      run: ./gradlew build check --stacktrace
    - name: Upload snapshot (main only)
      run: ./gradlew publish -PmavenCentralUsername=${{ secrets.SONATYPE_USERNAME }} -PmavenCentralPassword=${{ secrets.SONATYPE_PASSWORD }}
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && matrix.java_version == '16'
